In [1]:
class Employee():
    #for counting the number of employees, and for adding salaries and names.
    empNum, empName, empFam, empSal, empDep = 0, [], [], [], [];
    #This is my default constructor for the class to do the initialization work
    def __init__(self,name,family,salary,department): 
        self.empname = name #Storing the name in self.empname
        self.empfamily = family #Storing the family in self.empfamily
        self.empsalary = salary #Storing the salary in self.empsalary
        self.empdepartment = department #Storing the department in self.empdepartment
        Employee.empNum =  Employee.empNum + 1  #Counting the employees' numbers
        Employee.empName.append(name) #appends name attribute
        Employee.empFam.append(family) #appends family attribute
        Employee.empSal.append(salary)  #appends salaray attribute
        Employee.empDep.append(department)  #appends department attribute
        
    def average(self):
        sumSal = 0;
        for i in Employee.empSal:
            sumSal += int(i);
        return sumSal/len(Employee.empName)

class FullEmployee(Employee):
    def __init__(self,name,family,salary,department):
        Employee.__init__(self,name,family,salary,department)

fe1 = FullEmployee('Ali','ahmed','13000','Computer Science')
fe2 = Employee('Mohammed','Al-Mahzary','10000','Software Engineering')


In [4]:
# FullEmployee('Khalid','Dhabbah','13000','Computer Science');
# FullEmployee('Mohammed','Al-Mahzary','10000','Software Engineering');
# FullEmployee('Michael','Jack','15000','Networking')
print("The number of employees is: ", fe1.empNum)
print("The employees' names are: ", fe1.empName)
print("The employees' families are: ", fe1.empFam)
print("The employees' salaries are:", fe1.empSal)
print("The employees' departments are:", fe1.empDep)
print('The average salary is', FullEmployee.average(Employee))

The number of employees is:  2
The employees' names are:  ['Ali', 'Mohammed']
The employees' families are:  ['ahmed', 'Al-Mahzary']
The employees' salaries are: ['13000', '10000']
The employees' departments are: ['Computer Science', 'Software Engineering']
The average salary is 11500.0


In [22]:
import urllib.request
from bs4 import BeautifulSoup

URL = urllib.request.urlopen("https://en.wikipedia.org/wiki/Deep_learning")
s = BeautifulSoup(URL, "html.parser")

title = s.find('title')
links = s.find_all('a')

print("Title:", title.text)
print("Here is the links for this page:")
for l in links:
      print(l.get('href'))

Title: Deep learning - Wikipedia
Here is the links for this page:
None
#mw-head
#p-search
/wiki/Student_approaches_to_learning
/wiki/Artificial_neural_network
/wiki/Machine_learning
/wiki/Data_mining
/wiki/File:Kernel_Machine.svg
/wiki/Statistical_classification
/wiki/Cluster_analysis
/wiki/Regression_analysis
/wiki/Anomaly_detection
/wiki/Automated_machine_learning
/wiki/Association_rule_learning
/wiki/Reinforcement_learning
/wiki/Structured_prediction
/wiki/Feature_engineering
/wiki/Feature_learning
/wiki/Online_machine_learning
/wiki/Semi-supervised_learning
/wiki/Unsupervised_learning
/wiki/Learning_to_rank
/wiki/Grammar_induction
/wiki/Supervised_learning
/wiki/Statistical_classification
/wiki/Regression_analysis
/wiki/Decision_tree_learning
/wiki/Ensemble_learning
/wiki/Bootstrap_aggregating
/wiki/Boosting_(machine_learning)
/wiki/Random_forest
/wiki/K-nearest_neighbors_algorithm
/wiki/Linear_regression
/wiki/Naive_Bayes_classifier
/wiki/Artificial_neural_network
/wiki/Logistic_r

In [7]:
import requests
from bs4 import BeautifulSoup
html = requests.get("https://en.wikipedia.org/wiki/Deep_learning")
x = BeautifulSoup(html.content, "html.parser")
title = x.find("title")
print(title.string)
links = x.find_all('a')
for l in links:
      print(l.get('href'))

Deep learning - Wikipedia
None
#mw-head
#p-search
/wiki/Student_approaches_to_learning
/wiki/Artificial_neural_network
/wiki/Machine_learning
/wiki/Data_mining
/wiki/File:Kernel_Machine.svg
/wiki/Statistical_classification
/wiki/Cluster_analysis
/wiki/Regression_analysis
/wiki/Anomaly_detection
/wiki/Automated_machine_learning
/wiki/Association_rule_learning
/wiki/Reinforcement_learning
/wiki/Structured_prediction
/wiki/Feature_engineering
/wiki/Feature_learning
/wiki/Online_machine_learning
/wiki/Semi-supervised_learning
/wiki/Unsupervised_learning
/wiki/Learning_to_rank
/wiki/Grammar_induction
/wiki/Supervised_learning
/wiki/Statistical_classification
/wiki/Regression_analysis
/wiki/Decision_tree_learning
/wiki/Ensemble_learning
/wiki/Bootstrap_aggregating
/wiki/Boosting_(machine_learning)
/wiki/Random_forest
/wiki/K-nearest_neighbors_algorithm
/wiki/Linear_regression
/wiki/Naive_Bayes_classifier
/wiki/Artificial_neural_network
/wiki/Logistic_regression
/wiki/Perceptron
/wiki/Relevan

In [27]:
#axis = 1 is for the rows
#axis = 0 is for the cloumns
import numpy as np
rand = np.random.randint(1, high=20, size=15)
print(rand)
print("Reshaping the array to 3 by 5")
print(rand.reshape((3, 5)))

[17  7 18 17  4  2  2 15 19 12 15  8  9  8  8]
Reshaping the array to 3 by 5
[[17  7 18 17  4]
 [ 2  2 15 19 12]
 [15  8  9  8  8]]


In [28]:
print("The maximum value is:")
print(rand[rand.argmax()])
print("Replace the maximum value by 0:")
rand[rand.argmax()] = 0
print(rand)

The maximum value is:
19
Replace the maximum value by 0:
[17  7 18 17  4  2  2 15  0 12 15  8  9  8  8]


In [29]:
print(rand.reshape((3, 5)))

[[17  7 18 17  4]
 [ 2  2 15  0 12]
 [15  8  9  8  8]]


In [62]:
#axis = 1 is for the rows
#axis = 0 is for the cloumns
import numpy as np
rand = np.random.randint(1, high=20, size=15)
print(rand)
print("Reshaping the array to 3 by 5")
randmax = rand.reshape((3, 5))
print(randmax)

[16  8 19  8  6 16 19  1  6 11  9 15  2  1 13]
Reshaping the array to 3 by 5
[[16  8 19  8  6]
 [16 19  1  6 11]
 [ 9 15  2  1 13]]


In [63]:
maxInRows = np.max(randmax, axis=1, keepdims=False)
 
print('The max value in each row: ', maxInRows)

The max value in each row:  [19 19 15]


In [66]:
NewArray = np.where(randmax == np.max(randmax, axis=1, keepdims=True),0*randmax, randmax)
print(NewArray)

[[16  8  0  8  6]
 [16  0  1  6 11]
 [ 9  0  2  1 13]]


In [ ]:
#-1 means the number of rows which means I don't care
# 1 means the number of cloumns
reshape(-1,1)